# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e2ca487df2cb2d3cae30d03b0bc07ae7149cbf9796caf529b865a3c1d713f1b320c886af9369c6f3c90de87d591e3abbc5e243e8acff08062d47fd585587e0b

test:
  secret_key_base: 89c5d65dcb70eed3fbf7d497ca9ff2b68b56faf4428997f924b6c134450f373a39fd9f3406a7db56aaf34a1abeb967c3b099f568d61c2dd52e2a74e84782791b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
